# Generated by Django 5.0.6 on 2026-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('RECEPCIONISTA', 'Recepcionista'), ('GERENTE', 'Gerente'), ('SUPORTE', 'Suporte')], default='SUPORTE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_id',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensal'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_status',
            field=models.CharField(choices=[('NONE', 'Sem plano'), ('TRIALING', 'Período de testes'), ('ACTIVE', 'Ativo'), ('EXPIRED', 'Expirado')], default='NONE', max_length=20),
        ),
    ]
